### ISSUE TITLE
FormReCaptchaBlockDataInterface does not exist

### ISSUE THREAD

**Issue by balaboss78** [happymachines/magento2-module-custom-forms#4]
I run the command it shows this file no exist
![Screenshot (260)](https://user-images.githubusercontent.com/63161359/173838029-96fdbf5a-d266-4aa9-b681-578460aff3df.png)
and thanks for the module

**Comment by happymachines** [comment]
It looks like you might be missing the formbuilder recaptcha module. Can you check your `composer.json` file for `happymachines/magento2-module-custom-forms-re-captcha`, if you don't have that module installed require it using `composer require happymachines/magento2-module-custom-forms-re-captcha` and rerun the Magento setup commands.
