### ISSUE TITLE
Cannot instantiate interface

### ISSUE THREAD

**Issue by ghost** [happymachines/magento2-module-custom-forms#5]
Am testing the extension on Magento 2.4.5-p1 in developer mode, have installed both Page Builder and ReCaptcha successfully however when trying to install the Forms module I receive an error:
Cannot instantiate interface Magento\Framework\Filesystem\DriverInterface#0 /var/www/html/magento/framework/ObjectManager/ObjectManager.php(70) Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()

**Comment by happymachines** [comment]
This has been resolved in the latest release. Closing the issue.

**Comment by ghost** [comment]
Hi Geoff,

Thanks for the email and update.
I can confirm the composer install now works.
I did notice a small graphic error in the admin panel as below. Selecting the Action “select”. Thought I’d point it out.

***@***.***

Thanks very much again!

Regards
Jaimie
