### ISSUE TITLE
Form Action > Select

### ISSUE THREAD

**Issue by anathane** [happymachines/magento2-module-custom-forms#8]
Hi. I wanted to point out a minor graphic bug in the 2.4.5-p2 admin panel for the custom forms.  If you click Action > Select on the "Sample Contact Form" then the options seem hidden and require a scroll. I'm not sure if this is perhaps a Magento problem but wanted to point it out. Thanks!

**Comment by happymachines** [comment]
This is a core issue, you'll see the same visual issue on other UI listings in the admin such as customers and sales orders, so it's not necessarily related to the custom forms module.
